name: MediAssist
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.15.8
  table_calendar: ^1.2.2
  firebase_auth: any
  charts_flutter: ^0.6.0
  fcharts: ^0.0.11
  date_range_picker: ^1.0.5





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  cloud_firestore: any
  firebase_database: any


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
  - assets/login.jpg
  - assets/no_milk.jpg
  - assets/food.jpg
  - assets/vitaminK.jpg
  - assets/backimage.jpg
  - assets/logo.png
  - assets/shoes_01.png
  - assets/shoes_02.png
  - assets/store.png
  - assets/profile.png
  - assets/tab3.jpg
  - assets/tab2.jpg
  - assets/tab1.jpg
  - assets/tab4.jpg
  - assets/tab5.jpg
  - assets/tab6.jpg
  - assets/tab7.jpg
  - assets/tab8.jpg
  - assets/home.jpeg
  - assets/tick.png
  - assets/bi1.jpg
  - assets/skin.jpeg
  - assets/hair.png
  - assets/weightloss.jpg
  - assets/pregnantwomen.jpg
  - assets/bi2.jpg
  - assets/bi3.jpg
  - assets/white.png
  - assets/white2.png
  - assets/img1.jpg
  - assets/ma-logo.jpg
  - assets/rel3.jpg
  - assets/rel4.jpg
  - assets/images/oranges.png
  - assets/images/pear.png
  - assets/images/tomato.png
  - assets/avatars/avatar-1.jpg
  - assets/avatars/avatar-2.jpg
  - assets/avatars/avatar-3.jpg
  - assets/avatars/avatar-4.jpg
  - assets/avatars/avatar-5.jpg
  - assets/avatars/avatar-6.jpg
  - assets/avatars/default-avatar.jpg
  - images/medicationPill.jpg
  - images/patientpic.jpg
  - images/logo1.png
  - images/coverAccount.jpeg

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/Helvetica-Bold-Font.ttf

    - family: Raleway
      fonts:
        - asset: assets/Raleway-Regular.ttf

    - family: RalewayItalic
      fonts:
        - asset: assets/Raleway-LightItalic.ttf

    - family: CustomIcon
      fonts:
        - asset: assets/CustomIcon.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf

    - family: Medicine
      fonts:
        -  asset: assets/fonts/Medicine.ttf


  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
